system_node:
  ros__parameters:
    use_sim_time: false
    update_frequency: 10.0

    robot_footprint_frame: "base_link" # EasyNav necesita saber el marco de referencia del robot asi que asignamos el mismo que el del robot.





# PLANIFICADOR (Configurado según easynav_navmap_planner)
planner_node:
  ros__parameters:
    use_sim_time: false
    
    # Nombre clave que usará el nodo
    planner_types: ["AStarPlanner"]

    AStarPlanner:
      # El plugin correcto para el mapa de triángulos
      plugin: "easynav_navmap_planner/AStarPlanner" 
      
      # Parámetros
      cost_factor: 1.0        # Prioridad a la distancia vs coste del terreno
      continuous_replan: true # Recalcula si el robot se desvía

      layer: "inflated_obstacles" # Capa del mapa que el planificador usará para calcular el camino



# CONTROLADOR: Model Predictive Controller (MPC)
controller_node:
  ros__parameters:
    use_sim_time: false
    
    # Nombre que usaremos para cargar el plugin
    controller_types: ["MPCController"]

    # Configuración específica del MPC
    MPCController:
      plugin: "easynav_mpc_controller/MPCController"

      # PARÁMETROS DE PREDICCIÓN
      # Cuántos pasos hacia el futuro calcula.
      # Ponemos 20 para predecir 2 segundos completos.
      horizon_steps: 20  
      dt: 0.1            # Cada paso es 0.1 segundos (20 * 0.1 = 2.0s horizonte)

      # SEGURIDAD
      # Radio de colisión. ESTO ES UNA ESTIMACIÓN, hay que ajustarlo.
      safety_radius: 0.5

      # VELOCIDADES
      max_linear_velocity: 0.35   # 35 cm/s
      max_angular_velocity: 0.6   # Giro controlado

      # DEBUG
      verbose: false




# GESTOR DE SENSORES (Sustituye a nav2_sensor_bridge)
# Traduce los datos de los sensores al formato que EasyNav entiende
# Necesario para que el localizador funcione. Crea una nube de puntos a partir del LIDAR.
sensors_node:
  ros__parameters:
    use_sim_time: false
    
    # LISTA DE SENSORES
    sensors: ["lidar_frontal"]

    # CONFIGURACIÓN DE CADA SENSOR
    lidar_frontal:
      topic: "/scan_bridged" 
      # Tipo de mensaje exacto
      type: "sensor_msgs/msg/LaserScan" 
      
      # El grupo se autodetecta, pero forzamos 'points' por seguridad
      group: "points" 
    
    # Tiempo para olvidar lecturas viejas
    forget_time: 1.0




# LOCALIZADOR (Sustituye a nav2_amcl)

localizer_node:
  ros__parameters:
    use_sim_time: false
    
    # El nodo busca qué plugin cargar
    localizer_types: ["AMCLLocalizer"]

    # Configuración del plugin
    AMCLLocalizer:
      plugin: "easynav_navmap_localizer/AMCLLocalizer"
      num_particles: 400
      initial_pose:
        x: 0.0
        y: 0.0
        yaw: 0.0
        std_dev_xy: 0.1
        std_dev_yaw: 0.1
      
      downsampled_cloud_size: 0.1   # Cada cuánto reducir la nube de puntos para acelerar el proceso
      noise_translation: 0.05
      noise_rotation: 0.15
      noise_translation_to_rotation: 0.15
      
      # Le decimos la capa explícitamente.
      map_layer: "obstacles"
      # Esto crea un campo de probabilidad alrededor de las paredes.
      # Si el láser se va un poco, este campo lo atrae de vuelta al sitio.
      inflation_stddev: 0.3
      inflation_prob_min: 0.05

      # Damos más margen de tiempo
      transform_tolerance: 2.0
      

      compute_odom_from_tf: true




# GESTOR DE MAPAS (Sustituye a nav2_map_server)

maps_manager_node:
  ros__parameters:
    use_sim_time: false

    map_types: ["NavMapMapsManager"]

    # Configuración del NavMap
    NavMapMapsManager:
      plugin: "easynav_navmap_maps_manager/NavMapMapsManager"
      
      # El nombre del paquete donde está el mapa
      package: "diablo_test" 
      
      # Ruta relativa dentro del paquete
      occmap_path_file: "maps/mapa_tfg.yaml" 
      
      # Frecuencia de publicación
      freq: 1.0
      
      # Filtros opcionales
      # ACTIVAMOS EL FILTRO
      filters: ["inflation"]

      
      inflation:
        plugin: "easynav_navmap_maps_manager/NavMapMapsManager/InflationFilter"
        enabled: true
        # Ya no importa 'source_layer' porque el código lo autodetecta, 
        # pero deja la config de radios bien ajustada:
        inscribed_radius: 0.30  # Radio del robot (Zona Letal)
        inflation_radius: 0.55  # Radio total (Zona de Coste). TIENE QUE SER MAYOR.
        cost_scaling_factor: 5.0 # Cuánto penaliza el coste a medida que te acercas a los obstáculos
        output_layer: "inflated_obstacles"