# --- SYSTEM MAIN ---
system_main:
  ros__parameters:
    use_sim_time: false
    update_frequency: 10.0
    robot_footprint_frame: "base_footprint"
    robot_frame: "base_footprint"
    position_tolerance: 0.4
    height_tolerance: 999.0
    angle_tolerance: 0.5
    allow_preempt_goal: true

# --- PLANNER NODE ---
planner_node:
  ros__parameters:
    use_sim_time: false
    planner_types: ["CostmapPlanner"] 

    CostmapPlanner:
      plugin: "easynav_costmap_planner/CostmapPlanner"
      continuous_replan: true 
      goal_tolerance: 0.4
      transform_tolerance: 2.0
      layer: "inflation"
      robot_radius: 0.35 # Para que el planner tenga en cuenta el tamaño del robot al planificar rutas seguras. 

# --- MAPS MANAGER NODE ---
maps_manager_node:
  ros__parameters:
    use_sim_time: false
    map_types: ["CostmapMapsManager"] 

    CostmapMapsManager:
      plugin: "easynav_costmap_maps_manager/CostmapMapsManager"
      freq: 5.0 
      publish_frequency: 5.0 
      transform_tolerance: 2.0
      resolution: 0.05
      filters: ["obstacle","inflation"]
      
      obstacle:
        plugin: "easynav_costmap_maps_manager/CostmapMapsManager/ObstaclesFilter"
        enabled: true
        topic: "/map" 
        
      inflation:
        plugin: "easynav_costmap_maps_manager/CostmapMapsManager/InflationFilter"
        enabled: true
        inscribed_radius: 0.35
        inflation_radius: 0.45 
        cost_scaling_factor: 20.0 # A mas alto menos gordos los obstaculos

# --- LOCALIZER NODE ---
/localizer_node:
  ros__parameters:
    use_sim_time: false
    localizer_types: ["easynav_simple_localizer/AMCLLocalizer"]

    easynav_simple_localizer/AMCLLocalizer:
      plugin: "easynav_simple_localizer/AMCLLocalizer"
      # Los parametros de particulas ya dan igual, el codigo los ignora

# --- CONTROLLER NODE ---
controller_node:
  ros__parameters:
    use_sim_time: false
    controller_types: ["MPCController"]
    MPCController:
      plugin: "easynav_mpc_controller/MPCController"
      horizon_steps: 10
      dt: 0.1
      safety_radius: 0.35
      max_linear_velocity: 0.3
      max_angular_velocity: 0.5
      verbose: true
      transform_tolerance: 1.0

      fallback_goal_pos_tol: 0.2 # 2*Distancia a partir de la cual se activa la histeresis y el controlador proporcional.
      fallback_goal_yaw_tol: 0.5 # Ángulo (en radianes) a la que el robot considerará que ha alcanzado la orientación deseada.


# --- SENSOR NODE ---
sensors_node:
  ros__parameters:
    use_sim_time: false
    update_frequency: 10.0
    forget_time: 1.0
    
    # 1. LISTA DE IDENTIFICADORES
    sensors: ["lidar_frontal"]

    # 2. CONFIGURACIÓN DE CADA SENSOR DE LA LISTA
    lidar_frontal:
      topic: "/scan"                      
      type: "sensor_msgs/msg/LaserScan"   
