easynav_node:
  ros__parameters:
    use_sim_time: false
    update_frequency: 10.0


    # LOCALIZADOR (Sustituye a nav2_amcl)
    # Usa un plugin que implementa AMCL dentro de EasyNav.
    
    localizer_id: "AmclLocalizer"
    localizer_plugin: "easynav_plugins::AmclLocalizer"

    AmclLocalizer: # Parámetros específicos de filtrado de partículas (AMCL)
      min_particles: 500
      max_particles: 2000
      alpha1: 0.2  # Ruido odometría (rotación -> rotación)
      alpha2: 0.2  # Ruido odometría (rotación -> traslación)
      alpha3: 0.2  # Ruido odometría (traslación -> traslación)
      alpha4: 0.2  # Ruido odometría (traslación -> rotación)
      initial_pose_x: 0.0
      initial_pose_y: 0.0
      initial_pose_a: 0.0

    # PLANIFICADOR
    planner_id: "GridPlanner"   # Algoritmo Dijkstra en una cuadrícula
    # Otras posibilidades son "RapidlyExploringRandomTree" o "BreadthFirstSearch"
    planner_plugin: "easynav_plugins::GridPlanner" 

    # EL CONTROLADOR (Local Planner)
    controller_id: "VectorPursuit"  # Algoritmo tipo follow-the-carrot
    # Otras posibilidades son "DynamicWindowApproach" o "PID simple"
    controller_plugin: "easynav_plugins::VectorPursuitController"

    # Parámetros específicos del Controlador (VectorPursuit)
    VectorPursuit:
      desired_linear_vel: 0.5   # Velocidad máxima (m/s)
      lookahead_dist: 0.6       # "Mira" 60cm por delante de la línea
      rotation_correction_threshold: 0.5 # Si el error de ángulo es grande, gira en el sitio
      max_angular_vel: 1.0      # Velocidad de giro máxima (rad/s)

    # Parámetros del Robot
    robot_radius: 0.25          # Radio del robot para no chocar



# GESTOR DE MAPAS (Sustituye a nav2_map_server)

maps_manager_node:
  ros__parameters:
    use_sim_time: false

    # Aquí definimos la lista de tipos
    map_types: ["OccupancyGridMapManager"]

    # Y aquí la configuración del plugin
    OccupancyGridMapManager:
      plugin: "easynav_plugins::OccupancyGridMapManager"
      yaml_filename: "/home/adri/tfg_ws/src/diablo_test/maps/mapa_tfg.yaml"
      map_topic: "/map"
      subscribe_to_updates: false # En false para estático